services:

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: kea
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_HOST: db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: